export const messages = {
  de: {
    languageLabel: 'Deutsch',
    title: 'Black Myth: Wukong Countdown',
    day: 'Day',
    hour: 'Hour',
    minute: 'Min',
    second: 'Sec',
  },
  en: {
    languageLabel: 'English',
    title: 'Black Myth: Wukong Countdown',
    day: 'Day',
    hour: 'Hour',
    minute: 'Min',
    second: 'Sec',
  },
  es: {
    languageLabel: 'Español',
    title: 'Black Myth: Wukong Countdown',
    day: 'Day',
    hour: 'Hour',
    minute: 'Min',
    second: 'Sec',
  },
  fr: {
    languageLabel: 'Français',
    title: 'Black Myth: Wukong Countdown',
    day: 'Day',
    hour: 'Hour',
    minute: 'Min',
    second: 'Sec',
  },
  jp: {
    languageLabel: '日本語',
    title: '黒神話：悟空のカウントダウン',
    day: 'Day',
    hour: 'Hour',
    minute: 'Min',
    second: 'Sec',
  },
  kr: {
    languageLabel: '한국어',
    title: '검은 신화: 오공 카운트다운',
    day: 'Day',
    hour: 'Hour',
    minute: 'Min',
    second: 'Sec',
  },
  'zh-CN': {
    languageLabel: '简体中文',
    title: '《黑神话：悟空》发售倒计时',
    day: '天',
    hour: '时',
    minute: '分',
    second: '秒',
  },
  'zh-TW': {
    languageLabel: '繁體中文',
    title: '《黑神話：悟空》發售倒數計時',
    day: '天',
    hour: '時',
    minute: '分',
    second: '秒',
  },
}
