[[redirects]]
  from = "/umami-api/*"
  to = "https://api.umami.is/v1/:splat"
  force = true
  status = 200
  headers = {X-From = "Netlify", Accept = "application/json", x-umami-api-key = "k5z1qwy1alCl0t3ggniPrclbbeDOnv1v"}
