export const messages = {
  en: {
    languageLabel: 'English',
    title: 'Black Myth: Wukong Countdown',
    day: 'Day',
    hour: 'Hour',
    minute: 'Min',
    second: 'Sec',
    releaseSubtitle:
      'World simultaneous release at 10:00 AM on August 20, 2024 (UTC+8)',
    newVersionTips: 'New version available! Update now?',
    ok: 'OK',
    statsText: (stats) =>
      `Visitors <span class="text-[#a83d32]">${stats.visitors}</span>, Page Views <span class="text-[#a83d32]">${stats.pageViews}</span>`,
    installToDesktop: 'Install to Desktop',
    forum: 'Community: ',
    generateShareImage: 'Generate Image',
    share: 'Share',
    loading: 'Loading...',
    copied: 'Copied',
  },
  ja: {
    languageLabel: '日本語',
    title: '黒神話：悟空のカウントダウン',
    day: '日',
    hour: '時',
    minute: '分',
    second: '秒',
    releaseSubtitle: '2024年8月20日午前10時（UTC+8）に世界同時リリース',
    newVersionTips: '新しいバージョンがあります！アップデートしますか？',
    ok: 'OK',
    statsText: (stats) =>
      `訪問者 <span class="text-[#a83d32]">${stats.visitors}</span>人、ページビュー <span class="text-[#a83d32]">${stats.pageViews}</span>回`,
    installToDesktop: 'デスクトップにインストール',
    forum: 'コミュニティ：',
    generateShareImage: '画像を生成',
    share: '共有',
    loading: 'ロード中...',
    copied: 'コピーされました',
  },
  ko: {
    languageLabel: '한국어',
    title: '검은 신화: 오공 카운트다운',
    day: '일',
    hour: '시',
    minute: '분',
    second: '초',
    releaseSubtitle: '2024년 8월 20일 오전 10시 (UTC+8) 전세계 동시 발매',
    newVersionTips: '새 버전이 있습니다! 업데이트 하시겠습니까?',
    ok: '확인',
    statsText: (stats) =>
      `방문자 <span class="text-[#a83d32]">${stats.visitors}</span>명, 페이지 뷰 <span class="text-[#a83d32]">${stats.pageViews}</span>회`,
    installToDesktop: '데스크톱에 설치',
    forum: '커뮤니티: ',
    generateShareImage: '이미지 생성',
    share: '공유',
    loading: '로딩 중...',
    copied: '복사됨',
  },
  'zh-CN': {
    languageLabel: '简体中文',
    title: '《黑神话：悟空》发售倒计时',
    day: '日',
    hour: '时',
    minute: '分',
    second: '秒',
    releaseSubtitle: '2024年8月20日上午10点（UTC+8）发售',
    newVersionTips: '有新版本可用！是否更新？',
    ok: '确定',
    statsText: (stats) =>
      `已有<span class="text-[#a83d32]">${stats.visitors}</span>位访客，<span class="text-[#a83d32]">${stats.pageViews}</span>次浏览`,
    installToDesktop: '安装到桌面',
    forum: '交流社区：',
    generateShareImage: '生成图片',
    share: '分享',
    loading: '加载中...',
    copied: '已复制',
  },
  'zh-TW': {
    languageLabel: '繁體中文',
    title: '《黑神話：悟空》發售倒數計時',
    day: '日',
    hour: '時',
    minute: '分',
    second: '秒',
    releaseSubtitle: '2024年8月20日上午10點（UTC+8）發售',
    newVersionTips: '有新版本可用！是否更新？',
    ok: '確定',
    statsText: (stats) =>
      `已有<span class="text-[#a83d32]">${stats.visitors}</span>位訪客，<span class="text-[#a83d32]">${stats.pageViews}</span>次瀏覽`,
    installToDesktop: '安裝到桌面',
    forum: '交流社區：',
    generateShareImage: '生成圖片',
    share: '分享',
    loading: '加載中...',
    copied: '已複製',
  },
}
