export const messages = {
  en: {
    languageLabel: 'English',
    title: 'Black Myth: Wukong Countdown',
    day: 'Day',
    hour: 'Hour',
    minute: 'Min',
    second: 'Sec',
    releaseSubtitle:
      'World simultaneous release at 10:00 AM on August 20, 2024 (UTC+8)',
  },
  ja: {
    languageLabel: '日本語',
    title: '黒神話：悟空のカウントダウン',
    day: '日',
    hour: '時',
    minute: '分',
    second: '秒',
    releaseSubtitle: '2024年8月20日午前10時（UTC+8）に世界同時リリース',
  },
  ko: {
    languageLabel: '한국어',
    title: '검은 신화: 오공 카운트다운',
    day: '일',
    hour: '시',
    minute: '분',
    second: '초',
    releaseSubtitle: '2024년 8월 20일 오전 10시 (UTC+8) 전세계 동시 발매',
  },
  'zh-CN': {
    languageLabel: '简体中文',
    title: '《黑神话：悟空》发售倒计时',
    day: '日',
    hour: '时',
    minute: '分',
    second: '秒',
    releaseSubtitle: '2024年8月20日上午10点（UTC+8）发售',
  },
  'zh-TW': {
    languageLabel: '繁體中文',
    title: '《黑神話：悟空》發售倒數計時',
    day: '日',
    hour: '時',
    minute: '分',
    second: '秒',
    releaseSubtitle: '2024年8月20日上午10點（UTC+8）發售',
  },
}
